export interface Profile {
    id: string,
    name: string,
    dob: string,
    gender: string,
    phoneNumber: string,
    houseAddress: string,
    photograph: string,
    jobTitle: string,
    employeeId: string,
    employeeEmail: string,
    currentPosition: string,
    yearsOfExperience: number,
    currentWorkplace: string,
    qualification: string,
    fieldOfStudy: string,
    areaOfExpertise: string,
    projectsUndertaken: string,
}